# Precompiler options
CPP_OPTIONS= -DHOST=\"nurion-cray-fftw3\" \
			 -DMPI \
             -DscaLAPACK \
			 -Duse_collective \
             -Davoidalloc \
			 -Duse_shmem \
             -Dtbdyn  \
			 -DPROFILING

CPP        = cpp -P -traditional $*$(FUFFIX) $*$(SUFFIX) $(CPP_OPTIONS)

FC         = ftn 
FCL        = ftn -h noomp

FREE       = -f free

FFLAGS     = -e b -m 4 -h noomp
OFLAG      = -O3 -h fp3
OFLAG_IN   = $(OFLAG)
DEBUG      = -O0

BLAS       = 
LAPACK     =
BLACS      = 
SCALAPACK  = 
LLIBS      = -L$(HOME)/benchmark/lib -lfftw3 \
             -lsci_cray_mpi  

OBJECTS    = fftmpiw.o fftmpi_map.o fftw3d.o fft3dlib.o 
INCS       = -I$(HOME)/benchmark/include/fftw

# NCORE=1
OBJECTS_O0 += fftmpiw.o
OBJECTS_O3 += fftw3d.o fft3dlib.o

OFLAG_0    +=
OFLAG_1    += -h fp3 -h noomp
OFLAG_2    += -h fp3 -h noomp
OFLAG_3    += -h fp3 -h noomp

# For what used to be vasp.5.lib
CPP_LIB    = $(CPP)
FC_LIB     = $(FC)
CC_LIB     = cc
CFLAGS_LIB = -O2 
FFLAGS_LIB = -O2 
FREE_LIB   = $(FREE)

OBJECTS_LIB= linpack_double.o getshmem.o

# For the parser library
CXX_PARS   = CC 

LIBS       += parser
LLIBS      += -Lparser -lparser -lstdc++

# Normally no need to change this
SRCDIR     = ../../src
BINDIR     = ../../bin

#================================================
# GPU Stuff

CPP_GPU    = -DCUDA_GPU -DRPROMU_CPROJ_OVERLAP -DUSE_PINNED_MEMORY -DCUFFT_MIN=28 -UscaLAPACK

OBJECTS_GPU = fftmpiw.o fftmpi_map.o fft3dlib.o fftw3d_gpu.o fftmpiw_gpu.o

CC         = icc
CXX        = icpc
CFLAGS     = -fPIC -DADD_ -Wall -openmp -DMAGMA_WITH_MKL -DMAGMA_SETAFFINITY -DGPUSHMEM=300 -DHAVE_CUBLAS

CUDA_ROOT  ?= /usr/local/cuda/
NVCC       := $(CUDA_ROOT)/bin/nvcc -ccbin=icc
CUDA_LIB   := -L$(CUDA_ROOT)/lib64 -lnvToolsExt -lcudart -lcuda -lcufft -lcublas

GENCODE_ARCH    := -gencode=arch=compute_30,code=\"sm_30,compute_30\" \
                   -gencode=arch=compute_35,code=\"sm_35,compute_35\" \
                   -gencode=arch=compute_60,code=\"sm_60,compute_60\"

MPI_INC    = $(I_MPI_ROOT)/include64/
